tailwind.config = {
  theme: {
    extend: {
      fontFamily: {
        'cooper':      ['"Cooper Hewitt"', 'Inter', 'system-ui', 'sans-serif'],
        'garamond':    ['"EB Garamond"', 'Garamond', 'Georgia', 'serif'],
        'great-vibes': ['"Great Vibes"', 'Allura', 'cursive'],
        'inter':       ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        'rdc-bleu':       '#0095C9',
        'rdc-jaune':      '#FFF24B',
        'rdc-rouge':      '#DB3832',
        'rdc-bleu-fonce': '#17418A',
        'rdc-bleu-ciel':  '#0F89CB',
        'rdc-vert':       '#65B32E',
        'rdc-orange':     '#D44816',
        'rdc-orange-vif': '#ED7016',
        'rdc-sarcelle':   '#405D64',
        'rdc-pourpre':    '#9C0055',
        'rdc-or':         '#9F6E26',
        'rdc-noir':       '#323230',
        'rdc-bleu-inst':  '#174899',
        'rdc-brun':       '#6B5854',
        'rdc-indigo':     '#3E4D9C',
        'rdc-petrole':    '#115780',
        'rdc-olive':      '#89A331',
        'rdc-peche':      '#E58858',
        'rdc-cuivre':     '#A14E17',
        'rdc-ardoise':    '#193540',
        'rdc-beige':      '#CBAC7E',
        'rdc-gris-clair': '#AFB8BE',
        'rdc-emeraude':   '#1A806C',
        'rdc-or-fonce':   '#BD9A00',
        'rdc-creme':      '#F9E3D5',
        'rdc-acajou':     '#63230B',
        'rdc-gris-bleu':  '#899EAA',
        'rdc-brun-fonce': '#80602C',
        primary:          'var(--primary)',
        'primary-dark':   'var(--primary-dark)',
      },
      spacing: {
        'module':       '110px',
        'section':      '220px',
        'content-zone': '438px',
        'header-h':     '108px',
        'subtitle-h':   '269px',
        'logo-web':     '50px',
        'logo-social':  '110px',
        'ligne-min':    '53px',
      },
      borderRadius: {
        'sm':   '4px',
        'md':   '8px',
        'lg':   '12px',
        'xl':   '16px',
        '2xl':  '24px',
      },
      boxShadow: {
        'soft':  '0 1px 3px rgba(0,0,0,0.08)',
        'md':    '0 4px 12px rgba(0,0,0,0.08)',
        'lg':    '0 8px 24px rgba(0,0,0,0.12)',
        'xl':    '0 16px 48px rgba(0,0,0,0.16)',
        'glass': '0 8px 32px rgba(0,0,0,0.08), inset 0 1px 0 rgba(255,255,255,0.6)',
      },
    }
  }
}
